server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#设置feign 客户端超时时间（openFeign默认支持ribbon）
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 2000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.tl666.consumeroder.service.PaymentFeignService: debug