server:
  port: 8004

spring:
  application:
    name: payment-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tl19980504


mybatis:
  mapper-locations: classpath:mapper/*.xml    #mybatis的Mapper.xml文件所在路径
  type-aliases-package: com.tl666.springcloud.pojo    #所在pojo类的别名所在的包