server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true    #访问路径可以显示ip地址

spring:
  application:
    name: hystrix-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tl19980504

mybatis:
  mapper-locations: classpath:mapper/*.xml    #mybatis的Mapper.xml文件所在路径
  type-aliases-package: com.tl666.springcloud.pojo    #所在pojo类的别名所在的包